[master]
k8s-master ansible_host=111.88.247.16 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-pet

[workers]
k8s-worker1 ansible_host=89.169.131.25 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-pet
k8s-worker2 ansible_host=84.201.173.146 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-pet

[k8s_cluster:children]
master
workers
